origin_prof:
	g++ -o origin_prof ../kernel_main.cpp ../cloth_code_origin.cpp -pg -no-pie

trival_prof:
	g++ -o trival_prof ../kernel_main.cpp ../cloth_code_trival.cpp -pg


clean:
	rm origin_prof
	rm trival_prof
